### ISSUE TITLE
[memory] Replace Buffer trait with Concrete Type to Avoid Dynamic Dispatching

### ISSUE THREAD

**Issue by BrianZill** [demikernel/runtime#25]
Description
--------------

This Issue is a follow-on to Issue #21 and PR #22.

Basically, dynamic dispatching of the Buffer trait will result in extraneous memory allocations, so we're going to replace the Buffer trait with the concrete DataBuffer type (which will be changed internally to support buffers from different memory allocators).

**Comment by ppenna** [comment]
Enhancement introduced in PR https://github.com/demikernel/runtime/pull/27.
